base_url = "https://rknt.de"

title = "rknt"
description = "Personal page of Daniel Haarhoff"

compile_sass = false

build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
author="Daniel Haarhoff"

[markdown]
highlight_code = false
bottom_footnotes = true
smart_punctuation = true
